# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('lugares_cercanos', models.CharField(max_length=100)),
                ('historio_lugar', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('costo_entrada', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='places.Lugares'),
        ),
    ]
