# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dangerzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dangerzonlatlng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.dangerzone')),
            ],
        ),
        migrations.AlterField(
            model_name='lugares',
            name='historio_lugar',
            field=models.CharField(max_length=1000),
        ),
    ]
